ProjetoModeloDDD.MVC/ViewModels/AutoInfracaoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProjetoModeloDDD.MVC.ViewModels
{
    public class AutoInfracaoViewModel
    {

        [Key]
        public int AutoInfracaoId { get; set; }

        [Required(ErrorMessage = "Preencha o campo Gravidade.")]
        public int gravidade { get; set; }

        [Required(ErrorMessage = "Preencha o campo Atenuante.")]
        public Boolean atenuante { get; set; }

        [Required(ErrorMessage = "Preencha o campo Agravante.")]
        public Boolean agravante { get; set; }

        public string multa { get; set; }

        [ForeignKey("processo")]
        public int ProcessoId { get; set; }
        public ProcessoViewModel processo { get; set; }

    }
}

ProjetoModeloDDD.MVC/Controllers/AutoInfracaoController.cs
using AutoMapper;
using ProjetoModeloDDD.Application.Interface;
using ProjetoModeloDDD.Domain.Entities;
using ProjetoModeloDDD.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetoModeloDDD.MVC.Controllers
{
    public class AutoInfracaoController : Controller
    {

        private readonly IAutoInfracaoAppService _autoInfracaoApp;
        private readonly IProcessoAppService _processoApp;
        private readonly IFornecedorAppService _fornecedorApp;
        private readonly IEnderecoAppService _enderecoApp;

        public AutoInfracaoController(IAutoInfracaoAppService autoInfracaoApp, IProcessoAppService processoApp, IFornecedorAppService fornecedorApp, IEnderecoAppService enderecoApp)
        {
            _autoInfracaoApp = autoInfracaoApp;
            _processoApp = processoApp;
            _fornecedorApp = fornecedorApp;
            _enderecoApp = enderecoApp;
        }

        // GET: AutoInfracao/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AutoInfracao/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AutoInfracaoViewModel autoInfracao)
        {
            autoInfracao.processo = null;
            autoInfracao.multa = CalculaMulta(autoInfracao);
            var autoInfracaoDomain = Mapper.Map<AutoInfracaoViewModel, AutoInfracao>(autoInfracao);
            _autoInfracaoApp.Add(autoInfracaoDomain);
            
            return RedirectToAction("Details", autoInfracao);
        }

        // GET: AutoInfracao/Details
        public ActionResult Details(AutoInfracaoViewModel autoInfracao)
        {
            var processoViewModel = Mapper.Map<Processo, ProcessoViewModel>(_processoApp.GetById(autoInfracao.ProcessoId));
            var fornecedorViewModel = Mapper.Map<Fornecedor, FornecedorViewModel>(_fornecedorApp.GetById(processoViewModel.FornecedorId));
            var enderecoViewModel = Mapper.Map<Endereco, EnderecoViewModel>(_enderecoApp.GetById(fornecedorViewModel.EnderecoId));
            fornecedorViewModel.Endereco = enderecoViewModel;
            processoViewModel.Fornecedor = fornecedorViewModel;
            autoInfracao.processo = processoViewModel;
            return View(autoInfracao);
        }

        private string CalculaMulta(AutoInfracaoViewModel autoInfracao)
        {
            var ag = (autoInfracao.agravante == true) ? 1 : 0;
            var at = (autoInfracao.atenuante == true) ? 0.33 : 1;

            var multa = 500 + (((120000) * 0.10) + 120000) * (3*(ag + at)*autoInfracao.gravidade);

            return multa.ToString();
        }

    }
}

ProjetoModeloDDD.MVC/Views/AutoInfracao/Create.cshtml
@model ProjetoModeloDDD.MVC.ViewModels.AutoInfracaoViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Auto de Infração</h2>


@using (Html.BeginForm("Create", "AutoInfracao", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.processo.Fornecedor.Cnpj, htmlAttributes: new { @class = "control-label col-md-2" }, labelText: "CNPJ")
            <div class="col-md-10">
                @Html.EditorFor(model => model.processo.Fornecedor.Cnpj, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.processo.Fornecedor.Cnpj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.processo.Fornecedor.RazaoSocial, htmlAttributes: new { @class = "control-label col-md-2" }, labelText: "Razão Social")
            <div class="col-md-10">
                @Html.EditorFor(model => model.processo.Fornecedor.RazaoSocial, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.processo.Fornecedor.RazaoSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.processo.Fornecedor.ReceitaBruta, htmlAttributes: new { @class = "control-label col-md-2" }, labelText: "Receita Bruta")
            <div class="col-md-10">
                @Html.EditorFor(model => model.processo.Fornecedor.ReceitaBruta, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.processo.Fornecedor.ReceitaBruta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.processo.dataRelato, htmlAttributes: new { @class = "control-label col-md-2" }, labelText: "Data do Relato")
            <div class="col-md-10">
                @Html.EditorFor(model => model.processo.dataRelato, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.processo.dataRelato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.processo.relatoFiscalizacao, htmlAttributes: new { @class = "control-label col-md-2" }, labelText: "Relato da Fiscalização")
            <div class="col-md-10">
                @Html.EditorFor(model => model.processo.relatoFiscalizacao, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.processo.relatoFiscalizacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gravidade, htmlAttributes: new { @class = "control-label col-md-2" }, labelText: "Gravidade")
            <div class="col-md-10">
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    listItems.Add(new SelectListItem
                    {
                        Text = "1",
                        Value = "1",
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "2",
                        Value = "2"
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "3",
                        Value = "3"
                    });
                }
                @Html.DropDownListFor(model => model.gravidade, listItems, "Selecione")
                @*@Html.EditorFor(model => model.gravidade, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.gravidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.atenuante, htmlAttributes: new { @class = "control-label col-md-2" }, labelText: "Atenuante")
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.atenuante)
                    @Html.ValidationMessageFor(model => model.atenuante, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.agravante, htmlAttributes: new { @class = "control-label col-md-2" }, labelText: "Agravante")
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.agravante)
                    @Html.ValidationMessageFor(model => model.agravante, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <input type="hidden" name="ProcessoId" id="ProcessoId" value="@Model.processo.ProcessoId">
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Home", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoModeloDDD.MVC/Views/AutoInfracao/Details.cshtml
@model ProjetoModeloDDD.MVC.ViewModels.AutoInfracaoViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.processo.Fornecedor.Cnpj)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.processo.Fornecedor.Cnpj)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.processo.Fornecedor.RazaoSocial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.processo.Fornecedor.RazaoSocial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.processo.Fornecedor.ReceitaBruta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.processo.Fornecedor.ReceitaBruta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.processo.dataRelato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.processo.dataRelato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.processo.relatoFiscalizacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.processo.relatoFiscalizacao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.gravidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gravidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.atenuante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.atenuante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.agravante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.agravante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.multa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.multa)
        </dd>

    </dl>
</div>